name: Yeni Proje Ekle
description: Awesome Türkiye listesine yeni bir proje önerin.
title: "[Proje]: "
labels: ["enhancement"]
body:
  - type: input
    id: project_name
    attributes:
      label: Proje Adı
      placeholder: Örn: Nolymarket
    validations:
      required: true
  - type: input
    id: repo_url
    attributes:
      label: Repository URL
      placeholder: https://github.com/
    validations:
      required: true
