name: Yeni Proje Ekle
description: Awesome Türkiye listesine yeni bir proje önerin.
title: "[Proje]: <Proje Adı>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "## 🇹🇷 Awesome Türkiye'ye Hoş Geldin!\nLütfen kurallara uyduğundan emin ol."
  - type: input
    id: project_name
    attributes:
      label: Proje Adı
      placeholder: Örn: Nolymarket
    validations:
      required: true
  - type: input
    id: repo_url
    attributes:
      label: Repository URL
      placeholder: https://github.com/ersozberk/proje
    validations:
      required: true